# Generated by Django 2.1.4 on 2019-04-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_date', models.DateTimeField(verbose_name='energy date')),
                ('anomaly_type', models.IntegerField(default=0)),
                ('anomaly_comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_date', models.DateTimeField(verbose_name='energy date')),
                ('energy', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200)),
                ('production_line', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=20)),
                ('install_date', models.DateTimeField(verbose_name='installed date')),
            ],
        ),
        migrations.AddField(
            model_name='energy',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LineDetection.Facility'),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LineDetection.Facility'),
        ),
    ]
