# Generated by Django 2.1.4 on 2019-05-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LineDetection', '0003_facility_energy_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='production_amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=0)),
                ('production_date', models.DateTimeField(verbose_name='pruduction date')),
                ('amount', models.IntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LineDetection.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='production_goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LineDetection.Facility')),
            ],
        ),
    ]
