# Generated by Django 2.1.4 on 2019-05-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineDetection', '0005_auto_20190515_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='position',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='season',
        ),
        migrations.AddField(
            model_name='cluster',
            name='anomaly_comments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cluster',
            name='anomaly_condition',
            field=models.IntegerField(default=0),
        ),
    ]
