# Generated by Django 2.1.4 on 2019-05-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineDetection', '0006_auto_20190517_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='anomaly_comments',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
