# Generated by Django 2.1.4 on 2019-05-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineDetection', '0007_auto_20190517_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='anomaly_solve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='solved_comments',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
